### ISSUE TITLE
Posting to my page.

### ISSUE THREAD

**Issue by IngwiePhoenix** [splashlab/yii-facebook-opengraph#13]
I have a FaceBook page that should automatically receive new blog entries from the site and post them there as well. What are the lines of code needed to post to the page whose API key and secret I had supplied?

Kind regards, Ingwie.

**Comment by thaddeusmt** [comment]
Sorry, this issue is outside of the scope of support I'm offering for my extension.

The Facebook documentation for posting to a Facebook Page is here:
https://developers.facebook.com/docs/graph-api/reference/v2.2/page#publishing

Once you have authorized an account with the `manage_pages` permission and get the Page's access token, you can issue POST requests with the `Yii::app()->facebook->makeRequest()` method. There is an example in the README now of a basic POST request.

Here is a helpful article I just Googled for as well:
https://www.webniraj.com/2014/08/23/facebook-api-posting-as-a-page-using-graph-api-v2-x-and-php-sdk-4-0-x/
