### ISSUE TITLE
Non-composer version

### ISSUE THREAD

**Issue by ryonnsan** [splashlab/yii-facebook-opengraph#15]
Hi all,

Firstly, thank you for the awesome Yii plugin. I have been using this for years.
May I request to have the non-composer version to download?

Thank you in advance.

Regards,
Ronny

**Comment by thaddeusmt** [comment]
I looked in to this briefly, and without Composer you need to rig up a custom to make this work, since you are not using Composer's autoloader. Here are some relevant links:

* https://www.sammyk.me/using-the-facebook-sdk-v4-without-composer
* https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-4-autoloader-examples.md

I took a stab at it, adding a little section to the README and including an `autoload.php` file that should work.

I'm going to take the stance that I don't officially support using this without Composer at this time though.

Good luck!
